### ISSUE TITLE
Updating client via Git stomps local config

### ISSUE THREAD

**Issue by ghost** [OuterDeepSpace/OuterDeepSpace#30]
Currently, the game stores all client settings in [install]/client-pygame/var/osci.ini - this includes any changes the user makes post-launch, like saved passwords and option tweaks. Since this file is also in the repo, any time someone updates their client, their configuration is reset and their stored login is erased.

We should probably make this file contain the defaults for the client, rather than its current config; a second ini specific to the user could be generated in their home directory and given a higher priority than the one we bundle.

**Comment by Malxe** [comment]
Another option would be to modify the initial login UI element to have a field for the Server Address, which can be entered whether using an existing login on a fresh install, or during the New Account registration screen.  Then write that to osci.ini and pull from there on subsequent launches to display as it does with saved login info.

This would make the client package a little more friendly to custom and private servers since right now the client assumes www.ospace.net even if no .ini exists.

**Comment by FeziPrime** [comment]
#31

**Comment by ghost** [comment]
I've jotted that down over at #31 seeing as it could coexist and involves a slightly different unit of work.

**Comment by Ragora** [comment]
Fixed in #32
